apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplemodel-deployment
  namespace: fccltest
  labels:
    app: samplemodel
  annotations:
   kubernetes.io/change-cause: Sample model image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplemodel
  template:
    metadata:
      labels:
        app: samplemodel
    spec:
      containers:
      - name: samplemodel
        image: 192.168.131.125:8085/infinibrain/sample:v1
        imagePullPolicy: IfNotPresent
        command: ["sleep"]
        args: ["100000"]
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: my-secret
      tolerations:
      - key: "jetson"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
        
